LINE_TOKEN = "eUbzrVqurFmYr/hms1DUEo7FU+t47aQRkFmOUeULyN7PyKKteSSfv/VobijDw7qqDphhuFlGKHJCnfMleQ1XlC Jj2FRu2UJTYj9dAZUFIZeX6MbqM1pPoRImA27y6318kjuOQai0NXHxtV5toAUP4AdB04t89/1O/w1cDnyilFU="
LINE_USER_ID = "Ud25e9519467182c8b844df5260bccde5"
